OnlineJobSearch/OnlineJob/Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineJob.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace OnlineJob.Controllers
{
    public class AdminController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }



        public IActionResult DisplayAllAccount()
        {
            AccountList pst = new AccountList();
            List<Account> obj = pst.getAccount(string.Empty);
            return View(obj);
        }

        public IActionResult DeleteAccount(int id)
        {

            try
            {
            AccountList pstList = new AccountList();
            pstList.DeleteAccount(id);
            return RedirectToAction("DisplayAllAccount");
            }catch (Exception ex)
            {
                return RedirectToAction("Index");
            }



            
        }






        public IActionResult ListUser()
        {
            AccountUserList pst = new AccountUserList();
            List<AccountUser> obj = pst.getAccountUser(string.Empty);
            return View(obj);
        }


        public IActionResult DeleteAccountUser(int id)
        {
            try
            {
               AccountUserList pstList = new AccountUserList();
            pstList.DeleteAccountUser(id);
            return RedirectToAction("ListUser");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }



            
        }



        public IActionResult ListEmployee()
        {


            AccountEmployerList pst = new AccountEmployerList();
            List<AccountEmployer> obj = pst.getAccountEmployee(string.Empty);
            return View(obj);
        }

        public IActionResult DeleteAccountEmployee(int id)
        {

            try
            {
                AccountEmployerList pstList = new AccountEmployerList();
            pstList.DeleteAccountEmployee(id);
            return RedirectToAction("ListEmployee");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }




            
        }






        public IActionResult ListCV()
        {
            CVList pst = new CVList();
            List<CV> obj = pst.getCV(string.Empty);
            return View(obj);
        }


        public IActionResult DeleteCV(int id)
        {
            try
            {
                CVList pstList = new CVList();
                pstList.DeleteCV(id);
                return RedirectToAction("ListCV");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index");
            }




        }







    }
}

OnlineJobSearch/OnlineJob/Controllers/PostingController.cs
using Microsoft.AspNetCore.Mvc;
using OnlineJob.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace OnlineJob.Controllers
{
    public class PostingController : Controller
    {
        public IActionResult Index(int ? page)
        {

            PostingList pst = new PostingList();
            List<Posting> obj = pst.GetPosting(string.Empty);         
            return View(obj);
        }
        public IActionResult Create()
        {

            return View();
        }
        [HttpPost]
        public IActionResult Create(Posting pst)
        {
            if (ModelState.IsValid)
            {
                PostingList pstList = new PostingList();
                pstList.AddPosting(pst);
                return RedirectToAction("Index");
            }
            return View();

        }
        public IActionResult Details(string id)
        {
            PostingList pstList = new PostingList();
            List<Posting> obj = pstList.GetPosting(id);
            return View(obj.FirstOrDefault());

        }





        public IActionResult Delete(string id = "")
        {
            if (id.Equals(""))
            {
                return NotFound();
            }
            else
            {

                PostingList pstList = new PostingList();
                List<Posting> obj = pstList.GetPosting(id);
                return View(obj.FirstOrDefault());
            }
        }
        [HttpPost]
        public IActionResult Delete(int id)
        {

            PostingList pstList = new PostingList();
            pstList.DeletePosting(id);
            return RedirectToAction("Index");
        }






        public IActionResult Edit(string id = "")
        {
            PostingList pstList = new PostingList();
            List<Posting> obj = pstList.GetPostingEdit(id);
            return View(obj.FirstOrDefault());
        }
        [HttpPost]
        public IActionResult Edit(Posting pst)
        {
            PostingList pstList = new PostingList();
            pstList.UpdatePosting(pst);
            return RedirectToAction("Index");

        }
        public IActionResult Job()
        {
            PostingList pst = new PostingList();
            List<Posting> obj = pst.GetPosting(string.Empty);
            return View(obj);
        }
    




    }

    
   
}

OnlineJobSearch/OnlineJob/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineJob</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/css/site.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/css/normalize.min.css" rel="stylesheet" />
    <link href="~/css/animate.min.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/flaticon.css" rel="stylesheet" />
    <link href="~/css/fontawesome-all.min.css" rel="stylesheet" />
    <link href="~/css/magnific-popup.css" rel="stylesheet" />
    <link href="~/css/nice-select.css" rel="stylesheet" />
    <link href="~/css/owl.carousel.min.css" rel="stylesheet" />
    <link href="~/css/price_rangs.css" rel="stylesheet" />
    <link href="~/css/responsive.css" rel="stylesheet" />
    <link href="~/css/slick.css" rel="stylesheet" />
    <link href="~/css/slicknav.css" rel="stylesheet" />
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/css/themify-icons.css" rel="stylesheet" />


</head>
<body>
    <header>
        <!-- Header Start -->
        <div class="header-area header-transparrent">
            <div class="headder-top header-sticky">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-lg-3 col-md-2">
                            <!-- Logo -->
                            <div class="logo">
                                <a a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><img src="../assets/img/logo.png" alt=""></a>
                            </div>
                        </div>
                        <div class="col-lg-9 col-md-9">
                            <div class="menu-wrapper">
                                <!-- Main-menu -->
                                <div class="main-menu">
                                    <nav class="d-none d-lg-block">
                                        <ul id="navigation">
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Posting" asp-action="Job">Find a Jobs </a></li>
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Posting" asp-action="Index">Employer</a></li>
                                            <li><a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="Index">Admin</a></li>

                                            <li><a href="contact.html">Contact</a></li>
                                        </ul>
                                    </nav>
                                </div>
                                <!-- Header-btn -->
                                <div class="header-btn d-none f-right d-lg-block">
                                    <a href="#" class="btn head-btn1">Register</a>
                                    <a href="#" class="btn head-btn2">Login</a>
                                </div>
                            </div>
                        </div>
                        <!-- Mobile Menu -->
                        <div class="col-12">
                            <div class="mobile_menu d-block d-lg-none"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Header End -->


    </header>

    <div id="content">
        @RenderBody()
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - OnlineJob - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

    <!-- All JS Custom Plugins Link Here here -->
    <script src="../assets/js/vendor/modernizr-3.5.0.min.js"></script>
    <!-- Jquery, Popper, Bootstrap -->
    <script src="../assets/js/vendor/jquery-1.12.4.min.js"></script>
    <script src="../assets/js/popper.min.js"></script>
    <script src="../assets/js/bootstrap.min.js"></script>
    <!-- Jquery Mobile Menu -->
    <script src="../assets/js/jquery.slicknav.min.js"></script>

    <!-- Jquery Slick , Owl-Carousel Plugins -->
    <script src="../assets/js/owl.carousel.min.js"></script>
    <script src="../assets/js/slick.min.js"></script>
    <script src="../assets/js/price_rangs.js"></script>

    <!-- One Page, Animated-HeadLin -->
    <script src="../assets/js/wow.min.js"></script>
    <script src="../assets/js/animated.headline.js"></script>
    <script src="../assets/js/jquery.magnific-popup.js"></script>

    <!-- Scrollup, nice-select, sticky -->
    <script src="../assets/js/jquery.scrollUp.min.js"></script>
    <script src="../assets/js/jquery.nice-select.min.js"></script>
    <script src="../assets/js/jquery.sticky.js"></script>

    <!-- contact js -->
    <script src="../assets/js/contact.js"></script>
    <script src="../assets/js/jquery.form.js"></script>
    <script src="../assets/js/jquery.validate.min.js"></script>
    <script src="../assets/js/mail-script.js"></script>
    <script src="../assets/js/jquery.ajaxchimp.min.js"></script>

    <!-- Jquery Plugins, main Jquery -->
    <script src="../assets/js/plugins.js"></script>
    <script src="../assets/js/main.js"></script>
  

</body>
</html>